/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package toko;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import toko.koneksi;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class user extends javax.swing.JFrame {
private DefaultTableModel _table;
Connection _Cnn;
koneksi getCnn = new koneksi();
String Id_user, Nama_user, Alamat_user, username, password, akses, userakses, userkelas;
    public user(String user,String kelas) {
        initComponents();
        userakses = user ;
        userkelas = kelas ;
        LoadData();
        FormClear();
    }
private void LoadData(){
    String[] kolom = {"Id user", "Nama User", "Alamat User", "Username", "Akses"};
    _table = new DefaultTableModel(null,kolom){
        Class[] tipe = new Class [] {
            java.lang.String.class,
            java.lang.String.class,
            java.lang.String.class,
            java.lang.String.class,
            java.lang.String.class,
            java.lang.String.class
    };
        public Class getColumnClass(int columnindex) {
            return tipe [columnindex];
        }
        public boolean isCellEditable(int row, int col) {
            int cola = _table.getColumnCount();
            return (col < cola) ? false : true;
        }
        
                };
    tuser.setModel(_table);
    try {
        _Cnn = null;
        koneksi getCnn = new koneksi();
        _Cnn =getCnn.getConnection();
        HapusTabel();
        String sql = ""+
                "SELECT Id_user, Nama_user, Alamat_user, username, password, akses from karyawan order by Id_user asc";
        Statement stat = _Cnn.createStatement();
        ResultSet res = stat.executeQuery(sql);
        while(res.next()) {
            String xiduser = res.getString(1);
            String xnamauser = res.getString(2);
            String xalamatuser = res.getString(3);
            String xusername = res.getString(4);
            String xpassword = res.getString(5);
            String xakses = res.getString(6);
            Object[] data = {xiduser, xnamauser, xalamatuser,xusername, xpassword, xakses};
            _table.addRow(data);
        }
        tuser.getColumnModel().getColumn(0).setPreferredWidth(75);
        tuser.getColumnModel().getColumn(1).setPreferredWidth(200);
        tuser.getColumnModel().getColumn(2).setPreferredWidth(200);
        tuser.getColumnModel().getColumn(3).setPreferredWidth(200);
        tuser.getColumnModel().getColumn(4).setPreferredWidth(200);
        tuser.getColumnModel().getColumn(5).setPreferredWidth(100);
    } catch(Exception ex) {
        JOptionPane.showMessageDialog(this,"ERROR :" + ex);
    }
    
}
public void HapusTabel(){
    int row = _table.getRowCount();
    for(int i=0;i<row;i++){
        _table.removeRow(0);
    }
}
private void FormClear(){
    txtid.setEnabled(true);
    btnsimpan.setEnabled(true);
    btnedit.setEnabled(false);
    btnhapus.setEnabled(false);
    txtid.setText("");
    txtnama.setText("");
    txtalamat.setText("");
    txtuser.setText("");
    txtpass.setText("");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JTextField();
        cbakses = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnsimpan = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tuser = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("INPUT DATA USER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(364, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(346, 346, 346))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel2.setText("ID User");

        jLabel3.setText("Nama User");

        jLabel4.setText("Alamat User");

        jLabel5.setText("Username");

        jLabel6.setText("Password");

        jLabel7.setText("Akses");

        txtid.setText("jTextField1");

        txtnama.setText("jTextField2");

        txtalamat.setText("jTextField3");

        txtuser.setText("jTextField4");

        txtpass.setText("jTextField5");

        cbakses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "umum" }));
        cbakses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbaksesActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));

        btnsimpan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnedit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnhapus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tuser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tuserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tuser);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtid, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                                    .addComponent(txtnama)
                                    .addComponent(txtalamat)
                                    .addComponent(txtuser)
                                    .addComponent(txtpass))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbakses, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtid, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbakses, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        Id_user = txtid.getText();
        Nama_user = txtnama.getText();
        Alamat_user = txtalamat.getText();
        username = txtuser.getText();
        password = txtpass.getText();
        String cmbakses = cbakses.getSelectedItem().toString();
        akses = cmbakses;
            try{
                _Cnn = null;
                _Cnn = getCnn.getConnection();
                String sqlInsert = "insert into karyawan values ('"+Id_user+"',"
                + "'"+Nama_user+"',"
                        +"'"+Alamat_user+"',"
                            +"'"+username+"',"
                                +"'"+password+"',"
                                    +"'"+akses+"',"
                            +"'"+akses+"')";
                Statement statem = _Cnn.createStatement();
                statem.executeUpdate(sqlInsert);
                FormClear();
                LoadData();
                JOptionPane.showMessageDialog(null, "data disimpan");
                }catch(SQLException e){
                    JOptionPane.showConfirmDialog(null,"gagal disimpan","perhatian",
                        JOptionPane.DEFAULT_OPTION,JOptionPane.INFORMATION_MESSAGE);
                }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
Id_user = txtid.getText();
        Nama_user = txtnama.getText();
        Alamat_user = txtalamat.getText();
        username = txtuser.getText();
        password = txtpass.getText();
        String cmdkelas = cbakses.getSelectedItem().toString();
        akses = cmdkelas;
            try{
                _Cnn = null;
                _Cnn = getCnn.getConnection();
                String sqlInsert = "update karyawan set id_user = '"+Id_user+"',nama_user= '"+Nama_user+"', "
                        + "alamat_user = '"+Alamat_user+"',username = '"+username+"',password = '"+password+"',"
                            +"akses = '"+akses+"',kelas = '"+akses+"'where id_user='"+Id_user+"'";
 
               
               
                Statement statem = _Cnn.createStatement();
                statem.executeUpdate(sqlInsert);
                FormClear();
                LoadData();
                JOptionPane.showMessageDialog(null, "data disimpan");
                }catch(SQLException e){
                    JOptionPane.showConfirmDialog(null,"gagal disimpan","perhatian",
                        JOptionPane.DEFAULT_OPTION,JOptionPane.INFORMATION_MESSAGE);
                }        // TODO add your handling code here:
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
String iduser = tuser.getValueAt(tuser.getSelectedRow(), 0).toString();
       
        int jawab = JOptionPane.showConfirmDialog(this,"Apakah anda yakin ?? id USER : "+iduser,"Konfirmasi",
                JOptionPane.YES_NO_OPTION);
        if (jawab == JOptionPane.YES_OPTION) {
            try {
               _Cnn = null;
               _Cnn = getCnn.getConnection();
               String sqldelete = "delete from karyawan where id_user = '"+txtid.getText()+"'";
               
               Statement state = _Cnn.createStatement();
               state.executeUpdate(sqldelete);
               FormClear();
               LoadData();
               JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
           }catch(SQLException e) {
               JOptionPane.showConfirmDialog(null, "Data Tidak Berhasil dihapus !!!", "Informasi",
                       JOptionPane.DEFAULT_OPTION,JOptionPane.INFORMATION_MESSAGE);
           }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnhapusActionPerformed

    private void tuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tuserMouseClicked
        txtid.setEnabled(false);
        btnsimpan.setEnabled(false);
        btnedit.setEnabled(true);
        btnhapus.setEnabled(true);
 
            String iduser = tuser.getValueAt(tuser.getSelectedRow(),0).toString();
            try {
               _Cnn = null;
               _Cnn = getCnn.getConnection();
               String sql = "SELECT * FROM karyawan WHERE id_user = '" +iduser+"'";
               Statement stat = _Cnn.createStatement();
               ResultSet res = stat.executeQuery(sql);
               if(res.first()) {
                   txtid.setText(res.getString(1));
                   txtnama.setText(res.getString(2));
                   txtalamat.setText(res.getString(3));
                   txtuser.setText(res.getString(4));
                   txtpass.setText(res.getString(5));
                   cbakses.setSelectedItem(res.getString(6));
               }
               
           }catch(Exception ex) {
               JOptionPane.showMessageDialog(null, ex);
           }        // TODO add your handling code here:
    }//GEN-LAST:event_tuserMouseClicked

    private void cbaksesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbaksesActionPerformed
String akses;
if (cbakses.getSelectedIndex()==1) {
akses="admin";
}else {
akses = "umum";
}
    }//GEN-LAST:event_cbaksesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JComboBox<String> cbakses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tuser;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
